<?php
/*
 * Regles pour Foreignworld
 *
 */
 
 /*
 var gST="|ABAU|AJAQARASATAUAYBABEBGBLBMBQBRCCCFCGCHCICKCNCPCQCRCSCUDG|ANAUBABEBQBRBUBYCHCK|AQAJARASATAUAYBABEBGBLBMBQBRCCCFCGCHCICKCNCPCQCRCSCUDG|ARAJAQASATAUAYBABEBGBLBMBQBRCCCFCGCHCICKCNCPCQCRCSCUDG|ASAJAQARATAUAYBABEBGBLBMBQBRCCCFCGCHCICKCNCPCQCRCSCUDG|ATAJAQARASAUAYBABEBGBLBMBQBRCCCFCGCHCICKCNCPCQCRCSCUDG|AUABADAJANAPAQARASATAYBABEBGBLBMBOBQBRBUBYCCCFCGCHCICKCNCPCQCRCSCUCXDCDGDI|AYAJAQARASATAUBABEBGBLBMBQBRCCCFCGCHCICKCNCPCQCRCSCUDG|BAAJANAQARASATAUAYBEBGBLBMBQBRBUCCCFCGCHCICKCNCPCQCRCSCUDG|BEAJANAQARASATAUAYBABGBLBMBQBRBUCCCFCGCHCICKCNCPCQCRCSCUDCDG|BGAJAQARASATAUAYBABEBLBMBQBRCCCFCGCHCICKCNCPCQCRCSCUDG|BLAJAQARASATAUAYBABEBGBMBQBRCCCFCGCHCICKCNCPCQCRCSCUDG|BMAJAQARASATAUAYBABEBGBLBQBRCCCFCGCHCICKCNCPCQCRCSCUDG|BOAU|BQAJANAQARASATAUAYBABEBGBLBMBRBUCCCFCGCHCICKCNCPCQCRCSCUDG|BRAJANAQARASATAUAYBABEBGBLBMBQBUCCCFCGCHCICKCNCPCQCRCSCUDG|BUANAUBABEBQBRCHCKCQ|BYAU|CCAJAQARASATAUAYBABEBGBLBMBQBRCFCGCHCICKCNCPCQCRCSCUDG|CFAJAQARASATAUAYBABEBGBLBMBQBRCCCGCHCICKCNCPCQCRCSCUDG|CGAJAQARASATAUAYBABEBGBLBMBQBRCCCFCHCICKCNCPCQCRCSCUDG|CHAJANAQARASATAUAYBABEBGBLBMBQBRBUCCCFCGCICKCNCPCQCRCSCUDG|CIAJAQARASATAUAYBABEBGBLBMBQBRCCCFCGCHCKCNCPCQCRCSCUDG|CKAJANAQARASATAUAYBABEBGBLBMBQBRBUCCCFCGCHCICNCPCQCRCSCUDG|CNAJAQARASATAUAYBABEBGBLBMBQBRCCCFCGCHCICKCPCQCRCSCUDG|CPAJAQARASATAUAYBABEBGBLBMBQBRCCCFCGCHCICKCNCQCRCSCUDG|CQAJAKAQARASATAUAYBABEBGBLBMBQBRBUCCCFCGCHCICKCNCPCRCSCUDG|CRAJAQARASATAUAYBABEBGBLBMBQBRCCCFCGCHCICKCNCPCQCSCUDG|CSAJAQARASATAUAYBABEBGBLBMBQBRCCCFCGCHCICKCNCPCQCRCUDG|CTAU|CUAJAQARASATAUAYBABEBGBLBMBQBRCCCFCGCHCICKCNCPCQCRCSDG|DAAU|DCAUBE|DGAJAQARASATAUAYBABEBGBLBMBQBRCCCFCGCHCICKCNCPCQCRCSCU|";

var gSTD="|ABAUAG|AJAQAM|AJARAM|AJASAM|AJATAM|AJAUAM|AJAYAM|AJBAAM|AJBEAM|AJBGAM|AJBLAM|AJBMAM|AJBQAM|AJBRAM|AJCCAM|AJCFAM|AJCGAM|AJCHAM|AJCIAM|AJCKAM|AJCNAM|AJCPAM|AJCQAM|AJCRAM|AJCSAM|AJCUAM|AJDGAM|ANAUAAAQASAUAV|ANBAAQ|ANBEAQ|ANBQAQ|ANBRAQ|ANBUAQ|ANBYAS|ANCHAQ|ANCKAQ|AQAJAM|AQARAM|AQASAM|AQATAM|AQAUAM|AQAYAM|AQBAAM|AQBEAM|AQBGAM|AQBLAM|AQBMAM|AQBQAM|AQBRAM|AQCCAM|AQCFAM|AQCGAM|AQCHAM|AQCIAM|AQCKAM|AQCNAM|AQCPAM|AQCQAM|AQCRAM|AQCSAM|AQCUAM|AQDGAM|ARAJAM|ARAQAM|ARASAM|ARATAM|ARAUAM|ARAYAM|ARBAAM|ARBEAM|ARBGAM|ARBLAM|ARBMAM|ARBQAM|ARBRAM|ARCCAM|ARCFAM|ARCGAM|ARCHAM|ARCIAM|ARCKAM|ARCNAM|ARCPAM|ARCQAM|ARCRAM|ARCSAM|ARCUAM|ARDGAM|ASAJAM|ASAQAM|ASARAM|ASATAM|ASAUAM|ASAYAM|ASBAAM|ASBEAM|ASBGAM|ASBLAM|ASBMAM|ASBQAM|ASBRAM|ASCCAM|ASCFAM|ASCGAM|ASCHAM|ASCIAM|ASCKAM|ASCNAM|ASCPAM|ASCQAM|ASCRAM|ASCSAM|ASCUAM|ASDGAM|ATAJAM|ATAQAM|ATARAM|ATASAM|ATAUAM|ATAYAM|ATBAAM|ATBEAM|ATBGAM|ATBLAM|ATBMAM|ATBQAM|ATBRAM|ATCCAM|ATCFAM|ATCGAM|ATCHAM|ATCIAM|ATCKAM|ATCNAM|ATCPAM|ATCQAM|ATCRAM|ATCSAM|ATCUAM|ATDGAM|AUABAG|AUADAO|AUAJAM|AUANAAAEAEAQASAUAV|AUAPAE|AUAQAM|AUARAM|AUASAM|AUATAM|AUAYAM|AUBAAAABAEAFAHAIAMANAQ|AUBEAAABAEAFAIAMANAQ|AUBGAAAM|AUBLAM|AUBMAM|AUBOAS|AUBQAAAEAFAIAMAQ|AUBRAAAEAEAFAMAPAQAR|AUBUAAAEAQ|AUBYAS|AUCCAIAM|AUCFADAM|AUCGAM|AUCHAAAFAIAMANAQ|AUCIAM|AUCKABACAHAKAMAQ|AUCNAM|AUCPAM|AUCQAAABAEAFAHAIAMANAQ|AUCRAM|AUCSAM|AUCUAM|AUCXAT|AUDCAK|AUDGAM|AUDIAG|AYAJAM|AYAQAM|AYARAM|AYASAM|AYATAM|AYAUAM|AYBAAM|AYBEAM|AYBGAM|AYBLAM|AYBMAM|AYBQAM|AYBRAM|AYCCAM|AYCFAM|AYCGAM|AYCHAM|AYCIAM|AYCKAM|AYCNAM|AYCPAM|AYCQAM|AYCRAM|AYCSAM|AYCUAM|AYDGAM|BAAJAM|BAANAQ|BAAQAM|BAARAM|BAASAM|BAATAM|BAAUAAABAEAFAHAIAMANAQ|BAAYAM|BABEAAABAFAHAMAQ|BABGAAAM|BABLAM|BABMAM|BABQAFAMAQ|BABRAFAMAQ|BABUAQ|BACCAM|BACFAM|BACGAM|BACHAFAMAQ|BACIAM|BACKABAHAMAQ|BACNAM|BACPAM|BACQABAFAMAQ|BACRAM|BACSAM|BACUAM|BADGAM|BEAJAM|BEANAQ|BEAQAM|BEARAM|BEASAM|BEATAM|BEAUAAABAEAFAHAIAMANAQ|BEAYAM|BEBAAAABAFAHAMAQ|BEBGAM|BEBLAM|BEBMAM|BEBQAFAMAQ|BEBRAFAMAQ|BEBUAQ|BECCAM|BECFAM|BECGAM|BECHAFAMAQ|BECIAM|BECKAHAKAMAQ|BECNAM|BECPAM|BECQAFAMAQ|BECRAM|BECSAM|BECUAM|BEDCAK|BEDGAM|BGAJAM|BGAQAM|BGARAM|BGASAM|BGATAM|BGAUAAAM|BGAYAM|BGBAAAAM|BGBEAM|BGBLAM|BGBMAM|BGBQAM|BGBRAM|BGCCAM|BGCFAM|BGCGAM|BGCHAM|BGCIAM|BGCKAM|BGCNAM|BGCPAM|BGCQAM|BGCRAM|BGCSAM|BGCUAM|BGDGAM|BLAJAM|BLAQAM|BLARAM|BLASAM|BLATAM|BLAUAM|BLAYAM|BLBAAM|BLBEAM|BLBGAM|BLBMAM|BLBQAM|BLBRAM|BLCCAM|BLCFAM|BLCGAM|BLCHAM|BLCIAM|BLCKAM|BLCNAM|BLCPAM|BLCQAM|BLCRAM|BLCSAM|BLCUAM|BLDGAM|BMAJAM|BMAQAM|BMARAM|BMASAM|BMATAM|BMAUAM|BMAYAM|BMBAAM|BMBEAM|BMBGAM|BMBLAM|BMBQAM|BMBRAM|BMCCAM|BMCFAM|BMCGAM|BMCHAM|BMCIAM|BMCKAM|BMCNAM|BMCPAM|BMCQAM|BMCRAM|BMCSAM|BMCUAM|BMDGAM|BOAUAS|BQAJAM|BQANAQ|BQAQAM|BQARAM|BQASAM|BQATAM|BQAUAAAEAFAMAQ|BQAYAM|BQBAAFAMAQ|BQBEAFAMAQ|BQBGAM|BQBLAM|BQBMAM|BQBRAFAMAQ|BQBUAQ|BQCCAM|BQCFAM|BQCGAM|BQCHAFAMAQ|BQCIAM|BQCKAHAMAQ|BQCNAM|BQCPAM|BQCQAFAMAQ|BQCRAM|BQCSAM|BQCUAM|BQDGAM|BRAJAM|BRANAQAV|BRAQAM|BRARAM|BRASAM|BRATAM|BRAUAAAFAMAPAQARAS|BRAYAM|BRBAAFAMAQ|BRBEAFAMAQ|BRBGAM|BRBLAM|BRBMAM|BRBQAFAMAQ|BRBUAQ|BRCCAM|BRCFAM|BRCGAM|BRCHAFAMAQ|BRCIAM|BRCKABAMAQ|BRCNAM|BRCPAM|BRCQAFAMAQ|BRCRAM|BRCSAM|BRCUAM|BRDGAM|BUANAQ|BUAUAAAQ|BUBAAQ|BUBEAQ|BUBQAQ|BUBRAQ|BUCHAQ|BUCKAQ|BUCQAQ|BYAUAS|CCAJAM|CCAQAM|CCARAM|CCASAM|CCATAM|CCAUAM|CCAYAM|CCBAAM|CCBEAM|CCBGAM|CCBLAM|CCBMAM|CCBQAM|CCBRAM|CCCFAM|CCCGAM|CCCHAM|CCCIAM|CCCKAM|CCCNAM|CCCPAM|CCCQAM|CCCRAM|CCCSAM|CCCUAM|CCDGAM|CFAJAM|CFAQAM|CFARAM|CFASAM|CFATAM|CFAUADAM|CFAYAM|CFBAAM|CFBEAM|CFBGAM|CFBLAM|CFBMAM|CFBQAM|CFBRAM|CFCCAM|CFCGAM|CFCHAM|CFCIAM|CFCKAM|CFCNAM|CFCPAM|CFCQAM|CFCRAM|CFCSAM|CFCUAM|CFDGAM|CGAJAM|CGAQAM|CGARAM|CGASAM|CGATAM|CGAUAM|CGAYAM|CGBAAM|CGBEAM|CGBGAM|CGBLAM|CGBMAM|CGBQAM|CGBRAM|CGCCAM|CGCFAM|CGCHAM|CGCIAM|CGCKAM|CGCNAM|CGCPAM|CGCQAM|CGCRAM|CGCSAM|CGCUAM|CGDGAM|CHAJAM|CHANAQ|CHAQAM|CHARAM|CHASAM|CHATAM|CHAUAAAFAMANAQ|CHAYAM|CHBAAFAMAQ|CHBEAFAMAQ|CHBGAM|CHBLAM|CHBMAM|CHBQAFAMAQ|CHBRAFAMAQ|CHBUAQ|CHCCAM|CHCFAM|CHCGAM|CHCIAM|CHCKAMAQ|CHCNAM|CHCPAM|CHCQAFAM|CHCRAM|CHCSAM|CHCUAM|CHDGAM|CIAJAM|CIAQAM|CIARAM|CIASAM|CIATAM|CIAUAM|CIAYAM|CIBAAM|CIBEAM|CIBGAM|CIBLAM|CIBMAM|CIBQAM|CIBRAM|CICCAM|CICFAM|CICGAM|CICHAM|CICKAM|CICNAM|CICPAM|CICQAM|CICRAM|CICSAM|CICUAM|CIDGAM|CKAJAM|CKANAQ|CKAQAM|CKARAM|CKASAM|CKATAM|CKAUAAABACAHAKAMAQ|CKAYAM|CKBAABAHAMAQ|CKBEAHAKAMAQ|CKBGAM|CKBLAM|CKBMAM|CKBQAMAQ|CKBRAMAQ|CKBUAQ|CKCCAM|CKCFAM|CKCGAM|CKCHAMAQ|CKCIAM|CKCNAM|CKCPAM|CKCQAM|CKCRAM|CKCSAM|CKCUAM|CKDGAM|CNAJAM|CNAQAM|CNARAM|CNASAM|CNATAM|CNAUAM|CNAYAM|CNBAAM|CNBEAM|CNBGAM|CNBLAM|CNBMAM|CNBQAM|CNBRAM|CNCCAM|CNCFAM|CNCGAM|CNCHAM|CNCIAM|CNCKAM|CNCPAM|CNCQAM|CNCRAM|CNCSAM|CNCUAM|CNDGAM|CPAJAM|CPAQAM|CPARAM|CPASAM|CPATAM|CPAUAM|CPAYAM|CPBAAM|CPBEAM|CPBGAM|CPBLAM|CPBMAM|CPBQAM|CPBRAM|CPCCAM|CPCFAM|CPCGAM|CPCHAM|CPCIAM|CPCKAM|CPCNAM|CPCQAM|CPCRAM|CPCSAM|CPCUAM|CPDGAM|CQAJAM|CQAKAJ|CQAQAM|CQARAM|CQASAM|CQATAM|CQAUAAABAEAFAIALAMAQ|CQAYAM|CQBAAFAMAQ|CQBEAFAMAQ|CQBGAM|CQBLAM|CQBMAM|CQBQAFAMAQ|CQBRAFAMAQ|CQBUAQ|CQCCAM|CQCFAM|CQCGAM|CQCHAFAM|CQCIAM|CQCKABAM|CQCNAM|CQCPAM|CQCRAM|CQCSAM|CQCUAM|CQDGAM|CRAJAM|CRAQAM|CRARAM|CRASAM|CRATAM|CRAUAM|CRAYAM|CRBAAM|CRBEAM|CRBGAM|CRBLAM|CRBMAM|CRBQAM|CRBRAM|CRCCAM|CRCFAM|CRCGAM|CRCHAM|CRCIAM|CRCKAM|CRCNAM|CRCPAM|CRCQAM|CRCSAM|CRCUAM|CRDGAM|CSAJAM|CSAQAM|CSARAM|CSASAM|CSATAM|CSAUAM|CSAYAM|CSBAAM|CSBEAM|CSBGAM|CSBLAM|CSBMAM|CSBQAM|CSBRAM|CSCCAM|CSCFAM|CSCGAM|CSCHAM|CSCIAM|CSCKAM|CSCNAM|CSCPAM|CSCQAM|CSCRAM|CSCUAM|CSDGAM|CTAUAG|CUAJAM|CUAQAM|CUARAM|CUASAM|CUATAM|CUAUAM|CUAYAM|CUBAAM|CUBEAM|CUBGAM|CUBLAM|CUBMAM|CUBQAM|CUBRAM|CUCCAM|CUCFAM|CUCGAM|CUCHAM|CUCIAM|CUCKAM|CUCNAM|CUCPAM|CUCQAM|CUCRAM|CUCSAM|CUDGAM|DAAUAG|DCAUAK|DCBEAK|DGAJAM|DGAQAM|DGARAM|DGASAM|DGATAM|DGAUAM|DGAYAM|DGBAAM|DGBEAM|DGBGAM|DGBLAM|DGBMAM|DGBQAM|DGBRAM|DGCCAM|DGCFAM|DGCGAM|DGCHAM|DGCIAM|DGCKAM|DGCNAM|DGCPAM|DGCQAM|DGCRAM|DGCSAM|DGCUAM|";


var gD="02aSystran Babelfis91aReverso PROMT   95aEctaco Rustran  96aEctaco Poltran  97aIBM Alphaworks  90aLogoVista       07aCyber Trans     07bReverso Voila   08bFreeTranslation 09aSoftCatalá      94aLing98          04aSancho          03aInterTran (tm)  01aGPL Trans       99aAlmisbar        04bAmikai          04cWorldlingo      9AaTransLand       04dArcnet          09bParsit          9baNetat           9caTranstar        ";


var gL="AA*Mono-lingual  AFAfrikaans      AGAlbanian       AHArabic         AIBasque         AJBelarusan      AEBengali        IPBosnian        ICBreton         AKBulgarian      APCatalan        AQCebuano        ARChechen        AUChinese        IAChinese (pinyinIBChinese (yale) AWCroatian       BACzech          BFDanish         BKDutch          BPEnglish        BREsperanto      BUEstonian       BYFarsi          CAFinnish        CFFrench         CHFrisian        GVGalician       GWGeorgian       CKGerman         CLGerman (austr.)CPGreek          CQGreek (ancient)CSHawaiian       CUHebrew         CWHindi          DAHungarian      DCIcelandic      DDIlongo         DFIndonesian     DMIrish          DKItalian        DPJapanese       DRKazakh         DSKhmer          DUKorean         EALatin          ECLatvian        EDLithuanian     IKMalay          EEMaori          IUMongolian      EFNorwegian      EGOccitan        IDPersian        EHPolish         ELPortug. (braz.)EKPortuguese     EORomanian       IERotuman        EPRussian        EQSanskrit       ILSardinian      ERSerbian        ESSlovak         EUSlovenian      FASpanish        FCSpanish (eur.) FBSpanish (lat.) FDSwahili        FFSwedish        FGTagalog        FLTamil          FMThai           FNTibetan        FOTswana         FPTurkish        FQUkrainian      GAUkrainian      GDUrdu           GKVietnamese     GUWelsh          HFYiddish        HKZulu           ";


var slangs="<option value=1>Afrikaans<option value=9>Bulgarian<option value=13>Chinese<option value=16>Croatian<option value=17>Czech<option value=18>Danish<option value=19>Dutch<option value=20>English<option value=24>Finnish<option value=25>French<option value=29>German<option value=31>Greek<option value=36>Hungarian<option value=37>Icelandic<option value=39>Indonesian<option value=41>Italian<option value=42>Japanese<option value=45>Korean<option value=49>Malay<option value=52>Norwegian<option value=55>Polish<option value=56>Portug. (braz.)<option value=57>Portuguese<option value=58>Romanian<option value=60>Russian<option value=63>Serbian<option value=65>Slovenian<option value=66>Spanish<option value=67>Spanish (eur.)<option value=68>Spanish (lat.)<option value=69>Swahili<option value=70>Swedish<option value=75>Tswana<option value=77>Ukrainian<option value=81>Welsh";

var ntrg=38;


var dicos="<option>PLEASE READ<option>TEXT BELOW:<option><option selected>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</option><option><option><option><option><option><option><option><option><option><option>If this text<option>does not<option>disappear<option>once page<option>is loaded,<option>your browser<option>doesn't support<option>JavaScript.<option>Read about<option>compatibility<option>on the<option>homepage.";

var tarempty = "<option selected>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<option><option><option><option><option><option><option><option><option><option><option><option><option><option><option><option><option><option><option><option><option><option><option><option><option><option><option><option><option><option><option><option><option><option><option><option><option>";

var ndic = 10;

var chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";

var seli, sels, selt, seld, nsrc, curndic, seldi;
 */
	$homepage = "http://www.foreignword.com/Tools/transnow.htm";
	$url = "http://www.foreignword.com/Tools/transnow.htm";
	$outputEncoding = "UTF-8";
	$inputEncoding  = "UTF-8";
	$maxSize  = 5000;      //Limit
	$param['l']='0';
	$param['dic']='CyberTrans';
	//TextArea
	$textarea = "termx";
	$param[$textarea]='';
	//Language select
	$select = "trg";
	$param[$select]='';
	
	$select['source'] = "t_src";
	//<option value=1>Afrikaans<option value=9>Bulgarian<option value=13>Chinese<option value=16>Croatian<option value=17>Czech<option value=18>Danish<option value=19>Dutch<option value=20>English<option value=24>Finnish<option value=25>French<option value=29>German<option value=31>Greek<option value=36>Hungarian<option value=37>Icelandic<option value=39>Indonesian<option value=41>Italian<option value=42>Japanese<option value=45>Korean<option value=49>Malay<option value=52>Norwegian<option value=55>Polish<option value=56>Portug. (braz.)<option value=57>Portuguese<option value=58>Romanian<option value=60>Russian<option value=63>Serbian<option value=65>Slovenian<option value=66>Spanish<option value=67>Spanish (eur.)<option value=68>Spanish (lat.)<option value=69>Swahili<option value=70>Swedish<option value=75>Tswana<option value=77>Ukrainian<option value=81>Welsh
	$select['target'] = "t_trg";
	$select['both'] = "";

	$pairs=array();
	$pairs['en']['de']="en|de";
	$pairs['en']['es']="en|es";
	$pairs['en']['fr']="en|fr";
	$pairs['en']['it']="en|it";
	$pairs['en']['pt']="en|pt";
	$pairs['en']['ja']="en|ja";
	$pairs['en']['ko']="en|ko";
	$pairs['en']['zh']="en|zh-CN";
	$pairs['de']['en']="de|en";
	$pairs['de']['fr']="de|fr";
	$pairs['es']['en']="es|en";
	$pairs['fr']['en']="fr|en";
	$pairs['fr']['en']="fr|de";
	$pairs['it']['en']="it|en";
	$pairs['pt']['en']="pt|en";
	$pairs['ja']['en']="ja|en";
	$pairs['ko']['en']="ko|en";
	$pairs['zh']['en']="zh-CN|en";
	
	$delimiter_pair="|";
	$regex['start']="<textarea name=q rows=5 cols=45 wrap=PHYSICAL>";
	$regex['end']="</textarea>";
?>